language: node_js
node_js:
  - 8
  - 10
  - 11
  - 12
  - 13
services:
  - mongodb

before_script:
  # Wait because MongoDB does not immediately accept connections (https://docs.travis-ci.com/user/database-setup/#mongodb-does-not-immediately-accept-connections)
  - sleep 15
  - npm install
  - npm run standard-check
script:
  - node app.js
  - npm test
